# Generated by Django 5.1.6 on 2025-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('phone_mobile', models.CharField(max_length=50)),
                ('maker', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_model', models.CharField(blank=True, max_length=100, null=True)),
                ('bought_from_rama', models.BooleanField(default=False)),
                ('has_japanese_registration', models.BooleanField(default=False)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('condition_of_part', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
                ('more_details', models.TextField()),
                ('shipping', models.CharField(choices=[('Any', 'Any'), ('DHL', 'by DHL'), ('OCS', 'by OCS'), ('EMS', 'by EMS'), ('IN-CAR', 'IN-CAR')], default='Any', max_length=10)),
                ('in_car_code_chassis', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(max_length=50, unique=True, verbose_name='Stock Number')),
                ('part_name', models.CharField(max_length=255, verbose_name='Part Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
