name: rama_dbk_crm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.1.1
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/car_01.png
  - assets/images/car_02.jpg
  - assets/images/car_03.png
  - assets/images/logo.png
  - assets/images/Rama_logo.png
  - assets/images/mustang.png
  - assets/images/trucks.png
  - assets/images/vehicle_group.png
  - assets/images/car_yard.png
  - assets/images/president.jpg
