# Generated by Django 5.1.6 on 2025-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
