# Generated by Django 5.1.6 on 2025-03-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=50)),
                ('reg_year_from', models.PositiveIntegerField()),
                ('reg_year_to', models.PositiveIntegerField()),
                ('more_option', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('tel_mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('i_am', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
